source 'https://github.com/CocoaPods/Specs.git' # 公有源
source 'https://github.com/NJHu/NJSpecs.git' # NJ 私有源

platform :ios, '10.3'
use_frameworks!

target 'NJDYPlayer_Example' do

	inhibit_all_warnings!
	
#    , :modular_headers => true
    pod 'NJDYPlayer', :path => '../'
    #pod 'NJIJKPlayer', :git => 'https://github.com/NJHu/NJIJKPlayer.git', :branch => 'master'
    #pod 'NJIJKPlayer', :path => '../../NJIJKPlayer'

  target 'NJDYPlayer_Tests' do
    inherit! :search_paths

  end
end
